services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_ENV : Production
    environment:
      NODE_ENV: production
      SIGN_IN_REDIRECT_URL: http://localhost:3000/app/dashboard
      SIGN_OUT_REDIRECT_URL: http://localhost:3000/login
      CLIENT_ID: RdRCqz8e1wmQPmCy1EYcI19twr8a 
    ports:
      - 3000:3000